AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 pilartecno

Resources:
  
  ec2securitygroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !ImportValue vpcPILARTECNO-vpcID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0


  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0fc5d935ebf8bc3bc
      Tags:
        - Key: Name
          Value: ec2-pilartecno
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - Ref: "ec2securitygroup"
          DeleteOnTermination: 'true'
          SubnetId: !ImportValue vpcPILARTECNO-Subnetprivate