AWSTemplateFormatVersion: "2010-09-09"
Description: S3 finalpilartecno


Resources:  
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: bucket-finalpilartecno