name: Deploy to AWS

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  deploy:
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy S3
        run: |
          aws cloudformation deploy --template-file s3.yml --region us-east-1 --stack-name s3PILAR
          aws s3 cp s3.yml s3://bucket-finalpilartecno
      
      - name: Deploy VPC
        run: |
          aws cloudformation deploy --template-file vpc.yml --region us-east-1 --stack-name vpcPILARTECNO --parameter-overrides env=$GITHUB_REF_NAME
      
      - name: Deploy EC2
        run: |
          aws cloudformation deploy --template-file ec2.yml --region us-east-1 --stack-name ec2PILARTECNO